// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-WJI_HTbOPL8y-nd2ukMa560_qCvP9fo',
    appId: '1:154085845430:web:a8a6f7b626407f0b453917',
    messagingSenderId: '154085845430',
    projectId: 'store-app-9e742',
    authDomain: 'store-app-9e742.firebaseapp.com',
    storageBucket: 'store-app-9e742.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOWqCbyRJaf3QPFWOfoG5ONQc1YL7zCc',
    appId: '1:154085845430:android:b14e643be4e6430b453917',
    messagingSenderId: '154085845430',
    projectId: 'store-app-9e742',
    storageBucket: 'store-app-9e742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfm-wMjTXdHUb23K9Hb7-zJ_zusO8CXPc',
    appId: '1:154085845430:ios:5f0b1feb4015cc78453917',
    messagingSenderId: '154085845430',
    projectId: 'store-app-9e742',
    storageBucket: 'store-app-9e742.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );
}
